name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
  workflow_dispatch:

jobs:
  define-version:
    name: Define version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_draft.outputs.version || steps.canary.outputs.version || steps.testing.outputs.version }}
      version-type: ${{ steps.release_draft.outputs.version_type || steps.canary.outputs.version_type || steps.testing.outputs.version_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Get Release Draft version
        id: release_draft
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: |
          echo "version_type=draft" >> $GITHUB_OUTPUT
          version=${{ github.ref_name }}
          echo "version=${version#v}" >> $GITHUB_OUTPUT
        
      - name: Get Canary version
        id: canary
        if: ${{ !steps.release_draft.outputs.version && github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
        run: |
          echo "version_type=canary" >> $GITHUB_OUTPUT
          version=$(git describe --tags --long --exclude '*-*' 2>/dev/null || echo "v0.0.0-$(git rev-list --count HEAD)-g$(git rev-parse --short HEAD)")
          echo "version=${version#v}" >> $GITHUB_OUTPUT

      - name: Get Testing version
        id: testing
        if: ${{ !steps.release_draft.outputs.version && !steps.canary.outputs.version }}
        run: |
          echo "version_type=testing" >> $GITHUB_OUTPUT
          branch=$(git rev-parse --abbrev-ref HEAD)
          version=$(git describe --tags --long --exclude '*-*' 2>/dev/null || echo "v0.0.0-$(git rev-list --count HEAD)-g$(git rev-parse --short HEAD)")
          echo "version=${version#v}-${branch//\//-}" >> $GITHUB_OUTPUT

  upload-sources:
    name: Upload sources to conan remote
    runs-on: ubuntu-latest
    needs: [ define-version ]
    if: ${{ github.repository == 'openpresso/openpresso-proto' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Export to local cache
        run: conan export . --version=${{ needs.define-version.outputs.version }}

      - name: Upload to remote
        run: |
          conan remote add openpresso https://conan.cloudsmith.io/openpresso/${{ needs.define-version.outputs.version-type }}
          conan remote login -p ${{ secrets.CONAN_DEPLOY_KEY }} openpresso openpresso-ci
          conan upload openpresso_proto/${{ needs.define-version.outputs.version }} --confirm -r openpresso

  release-draft:
    name: Create release draft
    runs-on: ubuntu-latest
    needs: [ define-version ]
    if: ${{ needs.define-version.outputs.version-type == 'draft' && github.repository == 'openpresso/openpresso-proto' }}
    permissions:
      contents: write
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          generate_release_notes: true

      